config/routes.rb
Rails.application.routes.draw do
  resources :orders

  get 'users/new'

  get 'static_pages/home'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact_us'
  
  get 'cat' => 'rental_items#index'
  
  get 'signup' => 'users#new'
  
  
  get 'catAdmin' => 'rental_items#catAdmin'
  
  
  get 'accInfo' => 'sessions#accInfo'
  
  get 'booking' => 'orders#new'
  
  
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :rental_items
  resources :users
  

  root 'static_pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/models/rental_item.rb
class RentalItem < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX},
        uniqueness: true, case_sensitive: false
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def welcome
    render text: "Site Under Construction"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:email, :bike, :num, :start_date, :days, :contactNum, :user_id)
    end
end

app/controllers/rental_items_controller.rb
class RentalItemsController < ApplicationController
  before_action :set_rental_item, only: [:show, :edit, :update, :destroy]

  # GET /rental_items
  # GET /rental_items.json
  def index
    @rental_items = RentalItem.all
  end
  
  def catAdmin
    @rental_items = RentalItem.all
  end

  # GET /rental_items/1
  # GET /rental_items/1.json
  def show
  end

  # GET /rental_items/new
  def new
    @rental_item = RentalItem.new
  end

  # GET /rental_items/1/edit
  def edit
  end

  # POST /rental_items
  # POST /rental_items.json
  def create
    @rental_item = RentalItem.new(rental_item_params)

    respond_to do |format|
      if @rental_item.save
        format.html { redirect_to @rental_item, notice: 'Rental item was successfully created.' }
        format.json { render :show, status: :created, location: @rental_item }
      else
        format.html { render :new }
        format.json { render json: @rental_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_items/1
  # PATCH/PUT /rental_items/1.json
  def update
    respond_to do |format|
      if @rental_item.update(rental_item_params)
        format.html { redirect_to @rental_item, notice: 'Rental item was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_item }
      else
        format.html { render :edit }
        format.json { render json: @rental_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_items/1
  # DELETE /rental_items/1.json
  def destroy
    @rental_item.destroy
    respond_to do |format|
      format.html { redirect_to rental_items_url, notice: 'Rental item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_item
      @rental_item = RentalItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_item_params
      params.require(:rental_item).permit(:Item, :Type, :Category, :Description, :Rental_Rate)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in
      log_in user
      redirect_to user
    else
      # Display error message
      flash.now[:danger] = 'Invalid email Id / Password'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
  def accInfo
    redirect_to current_user
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact_us
  end
  
  def phoenixAdmin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def index
    @user = User.all
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Dublin Rental Bikes!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rental_items_helper.rb
module RentalItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in a user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns current user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Check if user logged in
  def logged_in?
    !current_user.nil?
  end
  
  # Log user out
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Dublin Rental Bike Company</a>
    Powered by: <a href="http://heroku.com/">HEROKU.COM</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-light bg-faded">
    <div class="container">
      <%= link_to "Dublin Rental Bikes", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Catalogue", cat_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Rent a Bike", booking_path %></li>
            <li><%= link_to "Account Info", accInfo_path %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Dublin Rental Bikes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
<body>
</html>

app/views/orders/Index.html.erb
<div class="page-header">

<h1>Orders listing</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Orders</div>
  <div class="panel-body">
    <p></p>

<table class="table">
    <tr>
      <th>Email</th>
      <th>Bike</th>
      <th>Num</th>
      <th>Start date</th>
      <th>Days</th>
      <th>Contactnum</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
    
      </div>

    <% @orders.each do |order| %>
      <tr>
        <td><%= order.email %></td>
        <td><%= order.bike %></td>
        <td><%= order.num %></td>
        <td><%= order.start_date %></td>
        <td><%= order.days %></td>
        <td><%= order.contactNum %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New Order', new_order_path %>

  </div>

  </div>

app/views/orders/_form.html.erb
<% provide(:title, "Booking") %>
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
    <%= f.label :user_id, "User ID Number (Available from Account Infromation Page)" %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="control-group">
    <%= f.label "Select Bike", class: 'control-label' %>
    <div class="controls">
      <%= f.select(:bike, options_for_select([['Mountain - Adult','Mountain - Adult'],['Mountain - Child','Mountain - Child'],
      ['Touring - Adult Male','Touring - Adult Male'],['Touring - Adult Female','Touring - Adult Female'],
      ['Touring - Child','Touring - Child']])) %>
    </div>

  <div class="field">
    <%= f.label :num, "Number of Bikes Required" %><br>
    <%= f.number_field :num %>
  </div>
  <div class="field">
    <%= f.label :start_date, "Rental Start Date" %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :days, "Number of Days" %><br>
    <%= f.number_field :days %>
  </div>
  <div class="field">
    <%= f.label :contactNum, "Contact Phone Number" %><br>
    <%= f.text_field :contactNum %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="page-header">

<h1>Orders listing</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Orders</div>
  <div class="panel-body">
    <p></p>

<table class="table">
    <tr>
      <th>Email</th>
      <th>Bike</th>
      <th>Num</th>
      <th>Start date</th>
      <th>Days</th>
      <th>Contactnum</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
    
      </div>

    <% @orders.each do |order| %>
      <tr>
        <td><%= order.email %></td>
        <td><%= order.bike %></td>
        <td><%= order.num %></td>
        <td><%= order.start_date %></td>
        <td><%= order.days %></td>
        <td><%= order.contactNum %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New Order', new_order_path %>

  </div>

  </div>

app/views/orders/new.html.erb
<h1>New Rental Booking</h1>

<%= render 'form' %>

<%= link_to 'Home', root_path, class: 'btn btn-success' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email Address:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Bike Selected:</strong>
  <%= @order.bike %>
</p>

<p>
  <strong>Number Required:</strong>
  <%= @order.num %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @order.start_date %>
</p>

<p>
  <strong>Number of Days:</strong>
  <%= @order.days %>
</p>

<p>
  <strong>Contact Number:</strong>
  <%= @order.contactNum %>
</p>



<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', booking_path %>

app/views/rental_items/_form.html.erb
<%= form_for(@rental_item) do |f| %>
  <% if @rental_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental_item.errors.count, "error") %> prohibited this rental_item from being saved:</h2>

      <ul>
      <% @rental_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Item %><br>
    <%= f.text_field :Item %>
  </div>
  <div class="field">
    <%= f.label :Type %><br>
    <%= f.text_field :Type %>
  </div>
  <div class="field">
    <%= f.label :Category %><br>
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Rental_Rate %><br>
    <%= f.text_field :Rental_Rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_items/catAdmin.html.erb
<% provide(:title, "Catalogue Admin") %>

<div class="page-header">

<h1>Catalogue Administration</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Catalogue 2016 - 2017</div>
  <div class="panel-body">
    <p>  This is the latest catalogue of rental items available from Dublin Rental Bikes</br></br>
    The rates displayed are the daily rental rate and all prices are VAT inclusive</p>

<table class="table">
  <tr>
      <th>Item</th>
      <th>Type</th>
      <th>Category</th>
      <th>Description</th>
      <th>Rental rate</th>
      <th colspan="3"></th>
  </tr>
  
  </div>
 
    <% @rental_items.each do |rental_item| %>
      <tr>
        <td><%= rental_item.Item %></td>
        <td><%= rental_item.Type %></td>
        <td><%= rental_item.Category %></td>
        <td><%= rental_item.Description %></td>
        <td><%= rental_item.Rental_Rate %></td>
        <td><%= link_to 'Show', rental_item %></td>
        <td><%= link_to 'Edit', edit_rental_item_path(rental_item) %></td>
        <td><%= link_to 'Destroy', rental_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New Rental item', new_rental_item_path, class: 'btn btn-success' %>
  </div>

  </div>

app/views/rental_items/edit.html.erb
<h1>Editing Rental Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental_item %> |
<%= link_to 'Back', rental_items_path %>

app/views/rental_items/index.html.erb
<% provide(:title, "Catalogue") %>

<div class="page-header">

<h1>Catalogue Items</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Catalogue 2016 - 2017</div>
  <div class="panel-body">
    <p>  This is the latest catalogue of rental items available from Dublin Rental Bikes</br></br>
    The rates displayed are the daily rental rate and all prices are VAT inclusive</p>

<table class="table">
  <tr>
      <th>Item</th>
      <th>Type</th>
      <th>Category</th>
      <th>Description</th>
      <th>Rental rate</th>
      <th colspan="3"></th>
  </tr>
  
  </div>
 
    <% @rental_items.each do |rental_item| %>
      <tr>
        <td><%= rental_item.Item %></td>
        <td><%= rental_item.Type %></td>
        <td><%= rental_item.Category %></td>
        <td><%= rental_item.Description %></td>
        <td><%= rental_item.Rental_Rate %></td>
        <td><%= link_to 'Show', rental_item %></td>
        <td><%= link_to 'Edit', edit_rental_item_path(rental_item) %></td>
        <td><%= link_to 'Destroy', rental_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New Rental item', new_rental_item_path, class: 'btn btn-success' %>
  </div>

  </div>




  

app/views/rental_items/new.html.erb
<h1>New Rental Item</h1>

<%= render 'form' %>

<%= link_to 'Back', rental_items_path %>

app/views/rental_items/show.html.erb
<div class="page-header">
  <h1>Rental Catalogue</h1>
</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">This is a Panel Heading</div>
  <div class="panel-body">

<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @rental_item.Item %>
</p>

<p>
  <strong>Type:</strong>
  <%= @rental_item.Type %>
</p>

<p>
  <strong>Category:</strong>
  <%= @rental_item.Category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rental_item.Description %>
</p>

<p>
  <strong>Rental rate:</strong>
  <%= @rental_item.Rental_Rate %>
</p>

<div class="panel-footer">

<%= link_to 'Edit', edit_rental_item_path(@rental_item), class: 'btn btn-info btn-xs' %> |
<%= link_to 'Back', rental_items_path, class: 'btn btn-primary btn-xs' %>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanations">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "errors") %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="page-header">

<h1>Contact Dublin Rental Bikes</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes</div>
  <div class="panel-body">
      
      <P>Dublin Rental Bikes has been proividing cost efficient bike rental to North and West Dublin since 2013</br></br>
      
      Our company offers bikes for adults and children of two types - Touring and Mountain bikes.  As our aim is to encourage the cusomters we 
      service to take full advantage of parks and countryside of North and West Dublin.  We do not provide bikes in the category of Racer.
      
      Operationing out of our large premises located in Airways Industrial estate which provides a great location to service our customer 
      needs providing them with easy access for for collection while also enabling us to provide a speedy delivery if required.</P>



</div>

app/views/static_pages/contact_us.html.erb
<% provide(:title, "Contact Us") %>

<div class="page-header">

<h1>Contact Dublin Rental Bikes</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Contact Information</div>
  <div class="panel-body">

<table class="table">
  <tr>
      <th>Address</th>
      <th>eMail</th>
      <th>Phone</th>
      <th colspan="2"></th>
  </tr>
  
  </div>
 
      <tr>
        <td>Unit 13 Boeing Driver</br>Airways Industrial Estate</br>Santry</br>Dublin 9</br></br>
        Office hours: </br>9:30 to 16:30 Mon - Fri</br>
        10:00 - 2:30 Sat</td>
        <td>drb@tbikes.tes</td>
        <td>+353 1 8569741</br></br>
        Lines open: </br>
        8:00 - 18:00 Mon - Fri</br>
        9:30 - 15:00 Sat</td>
      </tr>
</table>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
    
<h1> Welcome to Dublin Rental Bikes</h1>

  <h2>This is the home page for Dublin Rental Bikes</br></br>
    Providing cost efficient bike rental to north and west Dublin since 2013</br></br> 
  </h2>
  
  <h3><%= link_to "Create Account", signup_path, class: "btn btn-success" %></h3>
</div>

<%= link_to image_tag("BikeIcon.png", alt: "Bike logo"), 'http://www.dublin.ie/' %>

app/views/static_pages/phoenixAdmin.html.erb
<% provide(:title, "Administration") %>

<div class="page-header">

<h1>Administration Functions</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes - Administration</div>
  <div class="panel-body">
    <p>  Administration Functions for Dublin Rent Bikes</p>

<table class="table">
  <tr>
      <th>Description</th>
      <th colspan="3"></th>
  </tr>
  
  </div>
 
      <tr>
        <td><%= "Catalogue Maintenace Tasks" %></td>
        <td><%= link_to 'Access', catAdmin_path, class: 'btn btn-success' %></td>
      </tr>
      <tr>
        <td><%= "User Tasks" %></td>
        <td><%= link_to 'Access', userListing_path, class: 'btn btn-success' %></td>
      </tr>
      <tr>
        <td><%= "List Bookings" %></td>
        <td><%= link_to 'Access', phoenixList_path, class: 'btn btn-success' %></td>
      </tr>

</table>

<div class="panel-footer">
  <%= link_to 'Home', root_path, class: 'btn btn-success' %>
  </div>

  </div>

app/views/users/Index.html.erb
<div class="page-header">

<h1>User Listing</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Registered Accounts</div>
  <div class="panel-body">


<table class="table">
  <tr>
      <th>ID Number</th>
      <th>Name</th>
      <th>Email</th>
  </tr>
  
  </div>
 
    <% @user.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
  <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New user', signup_path, class: 'btn btn-success' %>
  </div>

  </div>

app/views/users/index.html.erb
<div class="page-header">

<h1>User Listing</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Registered Accounts</div>
  <div class="panel-body">


<table class="table">
  <tr>
      <th>ID Number</th>
      <th>Name</th>
      <th>Email</th>
  </tr>
  
  </div>
 
    <% @user.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
  <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New user', signup_path, class: 'btn btn-success' %>
  </div>

  </div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Account Information</h1>
</br>
<h2>User ID: <%= @user.id %></br></br>
Username: <%= @user.name %></br></br>
Email: <%= @user.email %></br></br>
Address: <%= @user.address %></h2></br>